name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2 # Adds a step to checkout the repository code
      - name: Setup dotnet
        run: dotnet build
      - name: npm build install
        run: npm install  
            npm run build
        working-directory: DotnetTemplate.Web
      - name: Run C# tests
        run: dotnet test
      - name: Typescript tests
        run: npm t
        working-directory: DotnetTemplate.Web
      - name: Run typescript linter
        run: npm run lint
        working-directory: DotnetTemplate.Web